# Change these first
owner: dimenspace # Your GitHub organization or username, where this repository lives
repo: aosp-uptime # The name of this repository

sites:
  - name: android-13.0.0_r3
    url: http://aospxref.com/android-13.0.0_r3/
  - name: android-12.0.0_r3
    url: http://aospxref.com/android-12.0.0_r3/
  - name: android-11.0.0_r21
    url: http://aospxref.com/android-11.0.0_r21/
  - name: android-10.0.0_r47
    url: http://aospxref.com/android-10.0.0_r47/
  - name: android-9.0.0_r61
    url: http://aospxref.com/android-9.0.0_r61/
  - name: android-8.1.0_r81
    url: http://aospxref.com/android-8.1.0_r81/
  - name: android-7.1.2_r39
    url: http://aospxref.com/android-7.1.2_r39/
  - name: android-7.0.0_r7
    url: http://aospxref.com/android-7.0.0_r7/
  - name: android-6.0.1_r9
    url: http://aospxref.com/android-6.0.1_r9/
  - name: android-5.1.1_r9
    url: http://aospxref.com/android-5.1.1_r9/
  - name: android-5.0.2_r3
    url: http://aospxref.com/android-5.0.2_r3/
  - name: android-5.0.2_r3
    url: http://aospxref.com/android-5.0.2_r3/
  - name: kernel-android14-6.1-lts
    url: http://aospxref.com/kernel-android14-6.1-lts/
  - name: kernel-android14-5.15-lts
    url: http://aospxref.com/kernel-android14-5.15-lts/
  - name: kernel-android13-5.15-lts
    url: http://aospxref.com/kernel-android13-5.15-lts/
  - name: kernel-android13-5.10-lts
    url: http://aospxref.com/kernel-android13-5.10-lts/
  - name: kernel-android12-5.10-lts
    url: http://aospxref.com/kernel-android12-5.10-lts/

assignees: # Users to assign downtime issues (optional)
  - tiann
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aospxref.com
  # baseUrl: /aosp-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AOSPXref Status Page
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
